[general]
working_directory = "C:/Dev"
live_config_reload = true

import = [
    "./fonts.toml",
]

[window]
dimensions = { columns = 112, lines = 27 }

[terminal]
shell = "pwsh"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{key = "F1", mods = "Control", action = "ToggleViMode"}]
