[general]
working_directory = "C:/Dev"
live_config_reload = true

import = [
    "./fonts.toml",
]

[window]
dimensions = { columns = 112, lines = 27 }

[terminal]
shell = "pwsh"

[mouse]
hide_when_typing = true

# Use Ctrl+Alt+Space to enter ViMode
