live_config_reload = true

import = [
    "~/.config/alacritty/ignite.toml",
    "~/.config/alacritty/fonts.toml",
]

[window]
dimensions = { columns = 125, lines = 30 }
padding = { x = 2, y = 0 }

[mouse]
hide_when_typing = true

# <key>, <mods>, <mode>, <action> | <chars>
[keyboard]
bindings = [{ key = "Escape", mods = "Shift", action = "ToggleViMode" }]
